/*
 * An OpenFlow application interface library.
 *
 * Author: Yasunobu Chiba
 *
 * Copyright (C) 2012 NEC Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2, as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */


#ifndef OXM_TLV_H
#define OXM_TLV_H

#include <openflow.h>

#define OXM_HEADER__(CLASS, FIELD, HASMASK, LENGTH) \
    (uint32_t)(((CLASS) << 16) | ((FIELD) << 9) | ((HASMASK) << 8) | (LENGTH))
#define OXM_HEADER(CLASS, FIELD, LENGTH) \
    OXM_HEADER__(CLASS, FIELD, 0, LENGTH)
#define OXM_HEADER_W(CLASS, FIELD, LENGTH) \
    OXM_HEADER__(CLASS, FIELD, 1, (LENGTH) * 2)
#define OXM_CLASS(HEADER) ((HEADER) >> 16)
#define OXM_FIELD(HEADER) (((HEADER) >> 9) & 0x7f)
#define OXM_TYPE(HEADER) (((HEADER) >> 9) & 0x7fffff)
#define OXM_HASMASK(HEADER) (((HEADER) >> 8) & 1)
#define OXM_LENGTH(HEADER) ((HEADER) & 0xff)

#define OXM_MAKE_WILD_HEADER(HEADER) \
        OXM_HEADER_W(OXM_CLASS(HEADER), OXM_FIELD(HEADER), OXM_LENGTH(HEADER))


#define OXM_OF_IN_PORT        OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IN_PORT, 4)
#define OXM_OF_IN_PHY_PORT    OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IN_PHY_PORT, 4)
#define OXM_OF_METADATA       OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_METADATA, 8)
#define OXM_OF_METADATA_W     OXM_HEADER_W(OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_METADATA, 8)
#define OXM_OF_ETH_DST        OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ETH_DST, 6)
#define OXM_OF_ETH_DST_W      OXM_HEADER_W(OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ETH_DST, 6)
#define OXM_OF_ETH_SRC        OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ETH_SRC, 6)
#define OXM_OF_ETH_SRC_W      OXM_HEADER_W(OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ETH_SRC, 6)
#define OXM_OF_ETH_TYPE       OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ETH_TYPE, 2)
#define OXM_OF_VLAN_VID       OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_VLAN_VID, 2)
#define OXM_OF_VLAN_VID_W     OXM_HEADER_W(OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_VLAN_VID, 2)
#define OXM_OF_VLAN_PCP       OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_VLAN_PCP, 1)
#define OXM_OF_IP_DSCP        OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IP_DSCP, 1)
#define OXM_OF_IP_ECN         OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IP_ECN, 1)
#define OXM_OF_IP_PROTO       OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IP_PROTO, 1)
#define OXM_OF_IPV4_SRC       OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IPV4_SRC, 4)
#define OXM_OF_IPV4_SRC_W     OXM_HEADER_W(OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IPV4_SRC, 4)
#define OXM_OF_IPV4_DST       OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IPV4_DST, 4)
#define OXM_OF_IPV4_DST_W     OXM_HEADER_W(OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IPV4_DST, 4)
#define OXM_OF_TCP_SRC        OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_TCP_SRC, 2)
#define OXM_OF_TCP_DST        OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_TCP_DST, 2)
#define OXM_OF_UDP_SRC        OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_UDP_SRC, 2)
#define OXM_OF_UDP_DST        OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_UDP_DST, 2)
#define OXM_OF_SCTP_SRC       OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_SCTP_SRC, 2)
#define OXM_OF_SCTP_DST       OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_SCTP_DST, 2)
#define OXM_OF_ICMPV4_TYPE    OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ICMPV4_TYPE, 1)
#define OXM_OF_ICMPV4_CODE    OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ICMPV4_CODE, 1)
#define OXM_OF_ARP_OP         OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ARP_OP, 2)
#define OXM_OF_ARP_SPA        OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ARP_SPA, 4)
#define OXM_OF_ARP_SPA_W      OXM_HEADER_W(OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ARP_SPA, 4)
#define OXM_OF_ARP_TPA        OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ARP_TPA, 4)
#define OXM_OF_ARP_TPA_W      OXM_HEADER_W(OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ARP_TPA, 4)
#define OXM_OF_ARP_SHA        OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ARP_SHA, 6)
#define OXM_OF_ARP_SHA_W      OXM_HEADER_W(OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ARP_SHA, 6)
#define OXM_OF_ARP_THA        OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ARP_THA, 6)
#define OXM_OF_ARP_THA_W      OXM_HEADER_W(OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ARP_THA, 6)
#define OXM_OF_IPV6_SRC       OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IPV6_SRC, 16)
#define OXM_OF_IPV6_SRC_W     OXM_HEADER_W(OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IPV6_SRC, 16)
#define OXM_OF_IPV6_DST       OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IPV6_DST, 16)
#define OXM_OF_IPV6_DST_W     OXM_HEADER_W(OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IPV6_DST, 16)
#define OXM_OF_IPV6_FLABEL    OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IPV6_FLABEL, 4)
#define OXM_OF_IPV6_FLABEL_W  OXM_HEADER_W(OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IPV6_FLABEL, 4)
#define OXM_OF_ICMPV6_TYPE    OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ICMPV6_TYPE, 1)
#define OXM_OF_ICMPV6_CODE    OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_ICMPV6_CODE, 1)
#define OXM_OF_IPV6_ND_TARGET OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IPV6_ND_TARGET, 16)
#define OXM_OF_IPV6_ND_SLL    OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IPV6_ND_SLL, 6)
#define OXM_OF_IPV6_ND_TLL    OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IPV6_ND_TLL, 6)
#define OXM_OF_MPLS_LABEL     OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_MPLS_LABEL, 4)
#define OXM_OF_MPLS_TC        OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_MPLS_TC, 1)
#define OXM_OF_MPLS_BOS       OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_MPLS_BOS, 1)
#define OXM_OF_PBB_ISID       OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_PBB_ISID, 4)
#define OXM_OF_PBB_ISID_W     OXM_HEADER_W(OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_PBB_ISID, 4)
#define OXM_OF_TUNNEL_ID      OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_TUNNEL_ID, 8)
#define OXM_OF_TUNNEL_ID_W    OXM_HEADER_W(OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_TUNNEL_ID, 8)
#define OXM_OF_IPV6_EXTHDR    OXM_HEADER  (OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IPV6_EXTHDR, 2)
#define OXM_OF_IPV6_EXTHDR_W  OXM_HEADER_W(OFPXMC_OPENFLOW_BASIC, OFPXMT_OFB_IPV6_EXTHDR, 2)


#endif // OXM_TLV_H


/*
 * Local variables:
 * c-basic-offset: 2
 * indent-tabs-mode: nil
 * End:
 */
